#!/usr/bin/env bash
set -euo pipefail
for database in moneybags_dev moneybags_test; do
  if ! psql --no-psqlrc -d postgres -Atc "SELECT 1 FROM pg_database WHERE datname='$database'" | rg -q 1; then
    createdb "$database"
  fi
done
go run . migrate
DATABASE_URL="$TEST_DATABASE_URL" go run . migrate
